--- #YAML:1.0
name:                Ham-Reference-Solar
version:             0.03
abstract:            Get basic solar data from the web that's useful for Amateur Radio applications.
license:             artistic2
author:              
    - Brad McConahay N8QQ <brad@n8qq.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    LWP::UserAgent:                0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
